x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: "50m"
    max-file: "10"
    compress: "true"

x-healthcheck: &default-healthcheck
  interval: 1s
  retries: 10
  timeout: 3s

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${HOST_UID:-1000}
        GROUP_ID: ${HOST_GID:-1000}
    image: 'laravel/app:latest'
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    depends_on:
      pgbouncer:
        condition: service_started
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - no-new-privileges:true
    networks:
      - stack
    ports:
      - "8000:8000"
    volumes:
      - './storage/app/public:/var/www/html/storage/app/public'
      - './storage/logs:/var/www/html/storage/logs'
    logging: *default-logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "--max-time", "10", "localhost:8000/up"]
      <<: *default-healthcheck

  pgsql:
    image: 'postgres:${POSTGRES_VERSION:-17}-alpine'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - no-new-privileges:true
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'stack-pgsql:/var/lib/postgresql/data'
      - '../backup:/backup'
    networks:
      - stack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      <<: *default-healthcheck
    restart: unless-stopped
    logging: *default-logging

  pgbouncer:
    image: bitnamilegacy/pgbouncer:latest
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      pgsql:
        condition: service_healthy
    environment:
      POSTGRESQL_HOST: pgsql
      POSTGRESQL_PORT: 5432
      PGBOUNCER_DATABASE: '${DB_DATABASE}'
      POSTGRESQL_USERNAME: '${DB_USERNAME}'
      POSTGRESQL_PASSWORD: '${DB_PASSWORD}'
      PGBOUNCER_POOL_MODE: session
      PGBOUNCER_AUTH_TYPE: md5
      PGBOUNCER_MAX_CLIENT_CONN: 500
      PGBOUNCER_DEFAULT_POOL_SIZE: 25
      PGBOUNCER_USERLIST: '"${DB_USERNAME}" "${DB_PASSWORD}"'
    networks:
      - stack

networks:
  stack:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  stack-pgsql:
    driver: local
